/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DialogRouteImport } from './routes/dialog'
import { Route as CompactRouteImport } from './routes/compact'
import { Route as IndexRouteImport } from './routes/index'

const DialogRoute = DialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompactRoute = CompactRouteImport.update({
  id: '/compact',
  path: '/compact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compact': typeof CompactRoute
  '/dialog': typeof DialogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compact': typeof CompactRoute
  '/dialog': typeof DialogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compact': typeof CompactRoute
  '/dialog': typeof DialogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compact' | '/dialog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compact' | '/dialog'
  id: '__root__' | '/' | '/compact' | '/dialog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompactRoute: typeof CompactRoute
  DialogRoute: typeof DialogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dialog': {
      id: '/dialog'
      path: '/dialog'
      fullPath: '/dialog'
      preLoaderRoute: typeof DialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compact': {
      id: '/compact'
      path: '/compact'
      fullPath: '/compact'
      preLoaderRoute: typeof CompactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompactRoute: CompactRoute,
  DialogRoute: DialogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
